description: 'Evals for analyzer'
prompts:
  - file://prompts/login.txt

providers:
  - id: openai:codex-sdk
    config:
      sandbox_mode: read-only
      enable_streaming: true
      working_dir: .

tests:
  - description: "Analyzer used"
    assert:
      - type: contains
        value: "## Analyzer"
  - description: "Contains all headings of the analyzer"
    assert:
      - type: contains-all
        value:
          - "Cyclomatic complexity"
          - "Test coverage"
          - "Spaghetti code"
          - "Method signature"
